sudo: required
services:
  - docker

before_install:
  - docker build -t VirtualizeStuff/docker-react -f Dockerfile.dev .

script:
  - docker run VirtualizeStuff/docker-react npm run test -- --coverage
